version: "3"

services:
  proxy:
    image: nginx:alpine
    build:
      context: .
    ports:
      - "20000:80"
    depends_on:
      - api1
      - api2
    networks:
      - brainweb-network

  api1:
    build:
      context: "./core/target/docker/brainweb/interview/build"
    ports:
      - "20001:80"
    networks:
      - brainweb-network

  api2:
    build:
      context: "./core/target/docker/brainweb/interview/build"
    ports:
      - "20002:80"
    networks:
      - brainweb-network

  db:
    build:
      context: "./core/src/main/resources/db/schema"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: brainweb
    networks:
      - brainweb-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - brainweb-network

  prometheus:
    image: prom/prometheus
    volumes:
      - "./core/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - brainweb-network

networks:
  brainweb-network:
    driver: bridge
